-- Reflex: reaction-time / aim-trainer game schema
-- Demonstrates: tables, a trigger, views, a stored function, and a stored procedure (PostgreSQL)

CREATE TABLE players (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  TEXT        NOT NULL UNIQUE,
    handle     TEXT,
    country    VARCHAR(2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE scores (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id   BIGINT      NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    mode        TEXT        NOT NULL CHECK (mode IN ('reaction', 'aim')),
    reaction_ms INTEGER,
    accuracy    NUMERIC(5,2),
    targets_hit INTEGER,
    raw_score   INTEGER     NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_scores_mode_score ON scores (mode, raw_score DESC);
CREATE INDEX idx_scores_player     ON scores (player_id);
CREATE INDEX idx_scores_created    ON scores (created_at);

-- Aggregate table kept up to date by a trigger (no application code maintains it).
CREATE TABLE mode_stats (
    mode        TEXT PRIMARY KEY,
    total_plays BIGINT      NOT NULL DEFAULT 0,
    best_score  INTEGER,
    avg_score   NUMERIC(10,2),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Append-only audit log, also written by the trigger.
CREATE TABLE score_audit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_id   BIGINT,
    player_id  BIGINT,
    mode       TEXT,
    raw_score  INTEGER,
    action     TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── TRIGGER ──────────────────────────────────────────────────────────────────
-- After every score insert: roll up mode_stats and append an audit row.
CREATE OR REPLACE FUNCTION trg_score_after_insert()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO mode_stats (mode, total_plays, best_score, avg_score, updated_at)
    VALUES (NEW.mode, 1, NEW.raw_score, NEW.raw_score, now())
    ON CONFLICT (mode) DO UPDATE SET
        total_plays = mode_stats.total_plays + 1,
        best_score  = GREATEST(mode_stats.best_score, NEW.raw_score),
        avg_score   = ROUND(
            ((mode_stats.avg_score * mode_stats.total_plays) + NEW.raw_score)
            / (mode_stats.total_plays + 1), 2),
        updated_at  = now();

    INSERT INTO score_audit (score_id, player_id, mode, raw_score, action)
    VALUES (NEW.id, NEW.player_id, NEW.mode, NEW.raw_score, 'INSERT');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER score_after_insert
    AFTER INSERT ON scores
    FOR EACH ROW
    EXECUTE FUNCTION trg_score_after_insert();

-- ── VIEWS ────────────────────────────────────────────────────────────────────
-- All-time best score per player per mode, ranked with a window function.
CREATE VIEW v_leaderboard AS
SELECT t.mode,
       t.player_id,
       t.handle,
       t.best_score,
       RANK() OVER (PARTITION BY t.mode ORDER BY t.best_score DESC) AS rank
FROM (
    SELECT s.mode, s.player_id, p.handle, MAX(s.raw_score) AS best_score
    FROM scores s
    JOIN players p ON p.id = s.player_id
    GROUP BY s.mode, s.player_id, p.handle
) t;

-- Same, but only today's scores.
CREATE VIEW v_daily_leaderboard AS
SELECT t.mode,
       t.player_id,
       t.handle,
       t.best_score,
       RANK() OVER (PARTITION BY t.mode ORDER BY t.best_score DESC) AS rank
FROM (
    SELECT s.mode, s.player_id, p.handle, MAX(s.raw_score) AS best_score
    FROM scores s
    JOIN players p ON p.id = s.player_id
    WHERE s.created_at::date = CURRENT_DATE
    GROUP BY s.mode, s.player_id, p.handle
) t;

-- Score distribution buckets per mode.
CREATE VIEW v_percentile_dist AS
SELECT mode,
       width_bucket(raw_score, 0, 1000, 10) AS bucket,
       COUNT(*) AS plays
FROM scores
GROUP BY mode, bucket;

-- ── FUNCTION ─────────────────────────────────────────────────────────────────
-- Where a score lands (0-100) versus everyone else in the same mode. Higher = better.
CREATE OR REPLACE FUNCTION fn_player_percentile(p_mode TEXT, p_score INTEGER)
RETURNS NUMERIC AS $$
DECLARE
    pct NUMERIC;
BEGIN
    SELECT ROUND(
        100.0 * COUNT(*) FILTER (WHERE raw_score <= p_score) / NULLIF(COUNT(*), 0), 1)
    INTO pct
    FROM scores
    WHERE mode = p_mode;
    RETURN COALESCE(pct, 0);
END;
$$ LANGUAGE plpgsql STABLE;

-- ── PROCEDURE ────────────────────────────────────────────────────────────────
-- Housekeeping: prune audit rows older than N days.  e.g. CALL sp_purge_audit(30);
CREATE OR REPLACE PROCEDURE sp_purge_audit(p_days INTEGER)
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM score_audit
    WHERE created_at < now() - make_interval(days => p_days);
END;
$$;
